import type { Category } from "./types";

export const CATEGORY_LABELS: Record<Category, string> = {
  fruit: "Fruits",
  vegetable: "Vegetables",
  grain: "Grains",
  meat: "Meat & Poultry",
  seafood: "Seafood",
  dairy: "Dairy",
  legume: "Legumes",
  beverage: "Beverages",
  herb_or_spice: "Herbs & Spices",
  nut_or_seed: "Nuts & Seeds",
  oil_or_fat: "Oils & Fats",
  egg: "Eggs",
  other: "Other Foods",
  alcoholic_beverage: "Alcoholic Beverages",
  candy_or_dessert: "Candy & Desserts",
  condiment_or_sauce: "Condiments & Sauces",
  snack_savory: "Savory Snacks",
};

export const CATEGORY_EMOJI: Record<Category, string> = {
  fruit: "🍎",
  vegetable: "🥦",
  grain: "🌾",
  meat: "🍗",
  seafood: "🐟",
  dairy: "🥛",
  legume: "🫘",
  beverage: "🥤",
  herb_or_spice: "🌿",
  nut_or_seed: "🥜",
  oil_or_fat: "🫒",
  egg: "🥚",
  other: "🍽️",
  alcoholic_beverage: "🍷",
  candy_or_dessert: "🍰",
  condiment_or_sauce: "🫙",
  snack_savory: "🍿",
};
